<?xml version="1.0"?>
<robot name="slam_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- PARAMETERS -->
  <xacro:property name="base_radius" value="0.18"/>
  <xacro:property name="base_height" value="0.12"/>
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.025"/>
  <xacro:property name="wheel_sep" value="0.27"/>
  <xacro:property name="caster_radius" value="0.053"/>
  <xacro:property name="lidar_radius" value="0.05"/>
  <xacro:property name="lidar_height" value="0.05"/>

  <!-- BASE FOOTPRINT -->
  <link name="base_footprint"/>

  <!-- BASE LINK -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
    </collision>

    <inertial>
  <mass value="8.0"/>
  <inertia
    ixx="0.25"
    ixy="0.0"
    ixz="0.0"
    iyy="0.25"
    iyz="0.0"
    izz="0.35"/>
</inertial>

  </link>

  <joint name="base_joint" type="fixed">
  <parent link="base_footprint"/>
  <child link="base_link"/>
  <origin xyz="0 0 ${wheel_radius + base_height/2}"/>
</joint>


  <!-- LEFT WHEEL -->
  <link name="left_wheel_link">
  <visual>
    <origin rpy="1.5708 0 0"/>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
    </geometry>
    <material name="black">
      <color rgba="0 0 0 1"/>
    </material>
  </visual>

  <collision>
    <origin rpy="1.5708 0 0"/>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
    </geometry>
  </collision>

  <inertial>
    <mass value="1.0"/>
    <inertia ixx="0.01" ixy="0.0" ixz="0.0"
             iyy="0.01" iyz="0.0"
             izz="0.01"/>
  </inertial>
</link>

<joint name="left_wheel_joint" type="continuous">
  <parent link="base_link"/>
  <child link="left_wheel_link"/>
  <origin xyz="0.03 ${wheel_sep/2} -${base_height/2}"/>
  <axis xyz="0 1 0"/>
</joint>

  <!-- RIGHT WHEEL -->
<link name="right_wheel_link">
  <visual>
    <origin rpy="1.5708 0 0"/>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
    </geometry>
    <material name="black">
      <color rgba="0 0 0 1"/>
    </material>
  </visual>

  <collision>
    <origin rpy="1.5708 0 0"/>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
    </geometry>
  </collision>

  <inertial>
    <mass value="1.0"/>
    <inertia ixx="0.01" ixy="0.0" ixz="0.0"
             iyy="0.01" iyz="0.0"
             izz="0.01"/>
  </inertial>
</link>

<joint name="right_wheel_joint" type="continuous">
  <parent link="base_link"/>
  <child link="right_wheel_link"/>
  <origin xyz="0.03 -${wheel_sep/2} -${base_height/2}"/>
  <axis xyz="0 1 0"/>
</joint>


  <!-- CASTER -->
  <link name="caster_link">
  <visual>
    <geometry>
      <sphere radius="${caster_radius}"/>
    </geometry>
    <material name="gray">
      <color rgba="0.5 0.5 0.5 1"/>
    </material>
  </visual>

  <collision>
    <geometry>
      <sphere radius="${caster_radius}"/>
    </geometry>
  </collision>

  <inertial>
    <mass value="0.3"/>
    <inertia ixx="0.005" ixy="0.0" ixz="0.0"
             iyy="0.005" iyz="0.0"
             izz="0.005"/>
  </inertial>
</link>
<joint name="caster_joint" type="fixed">
  <parent link="base_link"/>
  <child link="caster_link"/>
  <origin xyz="-0.12 0 -${base_height/2}"/>
</joint>


<!-- LIDAR LINK -->
 <link name="lidar_link">
  <visual>
    <geometry>
      <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
    </geometry>
    <material name="green">
      <color rgba="0 1 0 1"/>
    </material>
  </visual>

  <collision>
    <geometry>
      <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
    </geometry>
  </collision>

  <inertial>
    <mass value="0.2"/>
    <inertia ixx="0.005" ixy="0.0" ixz="0.0"
             iyy="0.005" iyz="0.0"
             izz="0.005"/>
  </inertial>
</link>

<joint name="lidar_joint" type="fixed">
  <parent link="base_link"/>
  <child link="lidar_link"/>
  <origin xyz="0 0 ${base_height/2 + lidar_height/2}"/>
</joint>

<gazebo reference="left_wheel_link">
  <mu1>3.0</mu1>
  <mu2>3.0</mu2>

  <kp>1000000.0</kp>
  <kd>100.0</kd>

  <slip1>0.0</slip1>
  <slip2>0.0</slip2>

  <fdir1>1 0 0</fdir1>
</gazebo>

<gazebo reference="right_wheel_link">
  <mu1>3.0</mu1>
  <mu2>3.0</mu2>

  <kp>1000000.0</kp>
  <kd>100.0</kd>

  <slip1>0.0</slip1>
  <slip2>0.0</slip2>

  <fdir1>1 0 0</fdir1>
</gazebo>

<gazebo reference="caster_link">
  <mu1>0.05</mu1>
  <mu2>0.05</mu2>

  <kp>1000000.0</kp>
  <kd>100.0</kd>

  <slip1>1.0</slip1>
  <slip2>1.0</slip2>
</gazebo>


<gazebo reference="base_link">
  <mu1>0.1</mu1>
  <mu2>0.1</mu2>

  <kp>1000000.0</kp>
  <kd>100.0</kd>
</gazebo>


<gazebo reference="lidar_link">
  <sensor type="ray" name="lidar_sensor">
    <always_on>true</always_on>
    <update_rate>15.0</update_rate>
    <visualize>true</visualize>

    <ray>
      <scan>
        <horizontal>
          <samples>360</samples>
          <resolution>1</resolution>
          <min_angle>-3.14159</min_angle>
          <max_angle>3.14159</max_angle>
        </horizontal>
      </scan>
      <range>
        <min>0.12</min>
        <max>10.0</max>
        <resolution>0.01</resolution>
      </range>
    </ray>

    <plugin name="gazebo_ros_laser" filename="libgazebo_ros_ray_sensor.so">
      <ros>
        <remapping>~/out:=scan</remapping>
      </ros>

      <!-- ðŸ”¥ THIS LINE FIXES YOUR ISSUE -->
      <output_type>sensor_msgs/LaserScan</output_type>

      <frame_name>lidar_link</frame_name>
    </plugin>

  </sensor>
</gazebo>

<gazebo>
  <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">

    <ros>
      <namespace>/</namespace>
    </ros>

    <left_joint>left_wheel_joint</left_joint>
    <right_joint>right_wheel_joint</right_joint>

    <wheel_separation>${wheel_sep}</wheel_separation>
    <wheel_radius>${wheel_radius}</wheel_radius>
    <wheel_diameter>${wheel_radius * 2}</wheel_diameter>

    <command_topic>cmd_vel</command_topic>
    <odometry_topic>odom</odometry_topic>

    <publish_odom>true</publish_odom>
    <publish_odom_tf>true</publish_odom_tf>
    <publish_wheel_tf>true</publish_wheel_tf>

    <odometry_frame>odom</odometry_frame>
    <robot_base_frame>base_footprint</robot_base_frame>

  </plugin>
</gazebo>

</robot>
